import Head from 'next/head'
import Image from 'next/image'
import TestSelect from '../components/TestSelect/index.js'
import TestShow from '../components/TestShow/index'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TestSelect/>

    </div>
  )
}
